# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          # FIXME: reenable this when there will be other than .dprint.json json file
          # - id: check-json
          #   exclude: ^\.dprint\.json$
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
            types_or: [yaml, markdown, json]
    - repo: https://github.com/adamchainz/pre-commit-dprint
      rev: v0.22.0
      hooks:
          - id: dprint
            types_or: [toml]
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.62.3
      hooks:
          - id: terraform_fmt
          - id: terraform_validate
