# https://prettier.io/docs/en/options.html
overrides:
    - files:
          - "*.yaml"
          - "*.yml"
          - "*.md"
          - "*.json"
          - "*.js"
      options:
          tabWidth: 4
          printWidth: 88
    # https://github.com/NiklasPor/prettier-plugin-go-template
    - files:
          - "blog/src/layouts/**/*.html"
      options:
          parser: go-template
          tabWidth: 4
          printWidth: 88
