baseURL = "https://imomaliev.github.io/blog/"
languageCode = "en-us"
title = "Blog"

[build]
# Used for hashing styles in development to work with TailwindCSS's jit
writeStats = true

[menu]
[[menu.main]]
pageRef = "/"
name = "Blog"

[[menu.main]]
pageRef = "/tils/"
name = "TILs"
