# https://gohugo.io/hosting-and-deployment/hosting-on-github/
name: github pages

on:
    push:
        branches:
            - main # Set a branch to deploy
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.14.0
                  cache: "npm"
                  # The action defaults to search for the dependency file
                  # (package-lock.json or yarn.lock) in the repository root, and uses
                  # its hash as a part of the cache key.
                  # https://github.com/actions/setup-node#caching-packages-dependencies
                  cache-dependency-path: "./blog/package-lock.json"

            - name: Install npm dependencies
              working-directory: "./blog/"
              run: npm ci

            - name: Build
              working-directory: "./blog/"
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "./blog/src/public"
